### ISSUE TITLE
event name for use in collcectionview

### ISSUE THREAD

**Issue by hamidish** [ilievmark/Basil.Behaviors#6]
i want use this for collectionview to translate images forever in page 
 <CollectionView.ItemTemplate>

                        <DataTemplate>
                            <Image Source="{Binding img}">
                                <Image.Behaviors>
                                    <e:EventToMultipleHandlersBehavior>
                                        <s:TranslateAnimation Length="600" XOffset="35" YOffset="20" />
                                        <s:TranslateAnimation Length="700" XOffset="43" YOffset="-15" Easing="{x:Static Easing.SpringIn}" />
                                        <s:TranslateAnimation Length="400" XOffset="-18" YOffset="-25" />
                                        <s:TranslateAnimation Length="800" XOffset="-60" YOffset="20" Easing="{x:Static Easing.SinOut}" />
                                    </e:EventToMultipleHandlersBehavior>
                                </Image.Behaviors>
                            </Image>

                        </DataTemplate>
                    </CollectionView.ItemTemplate>

but i dont know eventname ?

**Comment by ilievmark** [comment]
@hamidish
You can use x:Name="thisPage" attribute for page and its Appearing event
e:EventToMultipleHandlersBehavior can be configured at this point as
<e:EventToMultipleHandlersBehavior TargetSubscribeObject="{x:Reference thisPage}" EventName="Appearing">

And after that you can use CycledAnimationDecorator with configured Cycles property as you wish
If you want infinite animation, you can create own animation decorator like InfiniteCycleAnimationDecorator and copy source  from CycledAnimationDecorator, but use infinite cycle while(true). Dont forget, that page can be appeared multiple times, so you need to save state whenever animation running or not and DONT run it again.

So your code will be like
```
                        <Image Source="{Binding img}">
                            <Image.Behaviors>
                                <e:EventToMultipleHandlersBehavior TargetSubscribeObject="{x:Reference thisPage}" EventName="Appearing">
                                    <d:InfiniteCycleAnimationDecorator>
                                       <s:TranslateAnimation Length="600" XOffset="35" YOffset="20" />
                                       <s:TranslateAnimation Length="700" XOffset="43" YOffset="-15" Easing="{x:Static Easing.SpringIn}" />
                                       <s:TranslateAnimation Length="400" XOffset="-18" YOffset="-25" />
                                       <s:TranslateAnimation Length="800" XOffset="-60" YOffset="20" Easing="{x:Static Easing.SinOut}" />
                                    </d:InfiniteCycleAnimationDecorator>
                                </e:EventToMultipleHandlersBehavior>
                            </Image.Behaviors>
                        </Image>
```

**Comment by ilievmark** [comment]
@hamidish If you don't mind, I'll close this issue..
